
apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-service
    spec:
      containers:
        - name: demo-service
          image: sandbox.azurecr.io/demo-service
          ports:
          - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: demo-service
