apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: demopipeline 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demopipeline 
    spec:
      containers:
        - name: demopipeline 
          image: sandbox.azurecr.io/demopipeline
          ports:
          - containerPort: 8080